import * as THREE from './three.module.js';
import {recipeFor} from './recipes.mjs';
import {KitchenState,ingredients} from './kitchen-state.mjs';
const root=document.querySelector('.kitchen'),host=root.querySelector('.kitchen-scene'),shelf=root.querySelector('.ingredient-shelf'),toggle=root.querySelector('.burner-toggle'),select=root.querySelector('#food-select'),feedback=root.querySelector('.kitchen-feedback');
const state=new KitchenState(),objects=new Map(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){host.innerHTML='<p class="kitchen-fallback">Your browser couldn’t start the 3D kitchen. Enable hardware acceleration and reload to play.</p>';toggle.disabled=true;throw e;}
renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-6,6,4,-4,.1,100);camera.position.set(0,11,11);camera.lookAt(0,.15,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x758b72,2.5));const sun=new THREE.DirectionalLight(0xfff6df,3.2);sun.position.set(-4,9,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-8,right:8,top:8,bottom:-8});sun.shadow.bias=-.0005;scene.add(sun);const fill=new THREE.DirectionalLight(0xd4fbff,1.6);fill.position.set(5,5,-5);scene.add(fill);
const mat=(color,metalness=0,roughness=.55)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
function mesh(geo,material,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(parent,w,h,d,color,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),mat(color),parent,x,y,z);}
function ball(parent,r,color,x=0,y=0,z=0,sx=1,sy=1,sz=1){const m=mesh(new THREE.SphereGeometry(r,24,16),mat(color),parent,x,y,z);m.scale.set(sx,sy,sz);return m;}
function ring(parent,r,t,color,x,y,z){const m=mesh(new THREE.TorusGeometry(r,t,12,64),mat(color,.5,.28),parent,x,y,z);m.rotation.x=-Math.PI/2;return m;}
const floor=mesh(new THREE.PlaneGeometry(40,40),mat(0xd5ded7),scene);floor.rotation.x=-Math.PI/2;floor.position.y=-.1;floor.castShadow=false;
const stove=new THREE.Group();stove.position.set(1.3,0,-1.35);scene.add(stove);const body=box(stove,3.45,.38,3.25,0xe8efe7,0,.13,0);body.material=mat(0xe4e9e1,.25,.35);box(stove,3.1,.07,2.75,0x171d1b,0,.36,-.1);
const burner=mesh(new THREE.CylinderGeometry(1.06,1.06,.16,64),mat(0x353f3b,.75,.25),stove,0,.49,-.15);ring(stove,.78,.06,0x8c9991,0,.59,-.15);for(let i=0;i<4;i++){const a=i*Math.PI/2;const prong=box(stove,.13,.18,.78,0x3c4441,Math.sin(a)*.78,.64,-.15+Math.cos(a)*.78);prong.rotation.y=a;}
const knob=mesh(new THREE.CylinderGeometry(.25,.25,.16,32),mat(0x0d0d0d),stove,.85,.31,1.49);knob.rotation.x=Math.PI/2;knob.userData.burner=true;const knobLine=box(stove,.045,.14,.025,0xd0ff00,.85,.34,1.59);
const pan=new THREE.Group();pan.position.set(0,.73,-.15);stove.add(pan);const profile=[new THREE.Vector2(0,0),new THREE.Vector2(.9,0),new THREE.Vector2(1.22,.08),new THREE.Vector2(1.36,.30),new THREE.Vector2(1.33,.35),new THREE.Vector2(1.23,.28),new THREE.Vector2(1.12,.12),new THREE.Vector2(0,.12)];mesh(new THREE.LatheGeometry(profile,64),mat(0x303936,.75,.32),pan);ring(pan,1.32,.035,0xa9b8ad,0,.33,0);const handle=box(pan,1.65,.15,.34,0x161f1b,1.94,.21,0);handle.rotation.z=.06;box(pan,.30,.15,.39,0xb0beb4,1.3,.18,0);box(pan,.8,.025,.19,0xd0ff00,2.10,.30,0);
const bowlPos=new THREE.Vector3(1.4,0,2.4),bowl=new THREE.Group();bowl.position.copy(bowlPos);scene.add(bowl);const bp=[new THREE.Vector2(0,0),new THREE.Vector2(.48,0),new THREE.Vector2(.75,.12),new THREE.Vector2(1.02,.49),new THREE.Vector2(1.04,.66),new THREE.Vector2(.96,.68),new THREE.Vector2(.92,.51),new THREE.Vector2(.67,.22),new THREE.Vector2(.40,.13),new THREE.Vector2(0,.13)];mesh(new THREE.LatheGeometry(bp,64),mat(0xf4f4f4,.05,.22),bowl);ring(bowl,1.005,.035,0x00bcc8,0,.65,0);
function label(text,x,z){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#56665c';ctx.font='500 38px Arial';ctx.textAlign='center';ctx.fillText(text,256,61);const texture=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false}));s.position.set(x,.08,z);s.scale.set(2.5,.47,1);scene.add(s);}

const flames=new THREE.Group();stove.add(flames);for(let i=0;i<22;i++){const a=i/22*Math.PI*2;const f=mesh(new THREE.ConeGeometry(.08,.27,12),new THREE.MeshBasicMaterial({color:i%3?0x00bcc8:0xffc365,transparent:true,opacity:.85}),flames,Math.cos(a)*.92,.65,-.15+Math.sin(a)*.92);f.userData.phase=i;}
const fireLight=new THREE.PointLight(0x00bcc8,0,4);fireLight.position.set(1.3,.6,-1.5);scene.add(fireLight);flames.visible=false;
const steam=[];for(let i=0;i<14;i++){const s=mesh(new THREE.SphereGeometry(.09,8,8),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0,depthWrite:false}),scene);s.castShadow=false;steam.push(s);}
function buildFood(item,preview=false){const spec=ingredients.find(i=>i.id===item.type),g=new THREE.Group();g.userData.item=item;g.userData.colors=[];
 switch(item.type){
 case 'water':{const glass=mesh(new THREE.CylinderGeometry(.22,.18,.62,32,1,true),new THREE.MeshPhysicalMaterial({color:0xe8fbff,transparent:true,opacity:.35,roughness:.1,side:THREE.DoubleSide}),g,0,.32,0);mesh(new THREE.CylinderGeometry(.19,.16,.38,32),new THREE.MeshStandardMaterial({color:0x63cbe5,transparent:true,opacity:.8,roughness:.1}),g,0,.22,0);ring(g,.22,.015,0xd0f5ff,0,.64,0);break;}
 case 'flour':{mesh(new THREE.CylinderGeometry(.33,.28,.18,24),mat(0xa78b69),g,0,.1,0);ball(g,.30,0xfff4dd,0,.22,0,1,.6,1);ball(g,.13,0xffffff,.1,.34,0,1,.45,1);break;}
 case 'egg':ball(g,.47,0xfff5dd,0,.06,0,1,.17,.8);ball(g,.19,0xffc82e,.06,.15,0,1,.6,1);break;
 case 'chocolate':box(g,.66,.13,.50,spec.color,0,.08,0);for(let i=0;i<3;i++)for(let j=0;j<2;j++)box(g,.19,.065,.21,0x86513a,(i-1)*.21,.17,(j-.5)*.24);break;
 case 'broccoli':box(g,.14,.28,.16,0xa2c96b,0,.14,0);for(let i=0;i<6;i++){const a=i/6*6.28;ball(g,.18,spec.color,Math.cos(a)*.18,.36,Math.sin(a)*.18);}ball(g,.22,0x327d32,0,.48,0);break;
 case 'carrot':{const c=mesh(new THREE.ConeGeometry(.16,.8,24),mat(spec.color),g,0,.16,0);c.rotation.z=Math.PI/2;for(let i=0;i<3;i++){const leaf=box(g,.27,.055,.07,0x3e983e,.48,.17,(i-1)*.08);leaf.rotation.y=(i-1)*.5;}break;}
 case 'steak':{const s=ball(g,.42,spec.color,0,.13,0,1.25,.30,.82);s.rotation.y=.3;const fat=ring(g,.25,.025,0xffd6ba,.03,.25,0);fat.scale.set(1.2,.7,1);for(let i=0;i<3;i++){const stripe=box(g,.45,.012,.016,0xefaf9b,0,.25,(i-1)*.13);stripe.rotation.y=.35;}break;}
 case 'mushroom':mesh(new THREE.CylinderGeometry(.12,.15,.3,18),mat(0xf3e8d3),g,0,.15,0);ball(g,.34,spec.color,0,.37,0,1,.45,1);break;
 case 'tomato':ball(g,.29,spec.color,0,.28,0,1,.9,1);for(let i=0;i<5;i++){const l=box(g,.25,.025,.055,0x467836,0,.53,0);l.rotation.y=i*1.26;}break;
 case 'shrimp':{const s=mesh(new THREE.TorusGeometry(.24,.105,12,24,Math.PI*1.6),mat(spec.color),g,0,.13,0);s.rotation.x=-Math.PI/2;const tail=mesh(new THREE.ConeGeometry(.13,.25,3),mat(0xe5845c),g,.19,.11,-.18);tail.rotation.z=1.2;break;}
 case 'cheese':{const shape=new THREE.Shape();shape.moveTo(-.35,-.3);shape.lineTo(.35,-.3);shape.lineTo(.23,.3);shape.closePath();const m=mesh(new THREE.ExtrudeGeometry(shape,{depth:.2,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.025,bevelThickness:.025}),mat(spec.color),g,0,.23,0);m.rotation.x=Math.PI/2;break;}
 }
 g.traverse(o=>{if(o.isMesh)g.userData.colors.push({material:o.material,base:o.material.color.clone()});});g.rotation.y=Math.random()*.6-.3;g.position.set(-2.5,.1,0);g.userData.target=g.position.clone();if(!preview){scene.add(g);objects.set(item.id,g);}return g;}
function announce(message){feedback.textContent=message;}
function refresh(){const old=select.value;select.innerHTML='';if(!state.items.length)select.add(new Option('Nothing on the counter yet',''));for(const i of state.items){const spec=ingredients.find(s=>s.id===i.type);select.add(new Option(`${i.dish?.name||spec.name} ${i.id} · ${i.cooked?'cooked':i.progress>0?'cooking':'raw'} · ${i.zone}`,i.id));}if(state.items.some(i=>String(i.id)===old))select.value=old;root.querySelector('.served-count').textContent=`${state.items.filter(i=>i.zone==='bowl').length} served`;root.querySelectorAll('[data-move]').forEach(b=>b.disabled=!state.items.length);}
function newFood(type){const item=state.add(type);if(!item){announce('Counter full. Start fresh to make another dish.');return null;}buildFood(item);refresh();select.value=item.id;return item;}
function put(item,zone,point){const g=objects.get(item.id);if(!state.move(item,zone)){announce('Cook this ingredient in the pan before serving.');return false;}let x,z,y;
 if(zone==='pan'){const n=state.items.filter(i=>i.zone==='pan'&&i!==item).length,a=n*2.4,r=Math.min(.85,.25+Math.sqrt(n)*.16);x=1.3+Math.cos(a)*r;z=-1.5+Math.sin(a)*r;y=.88;}
 else if(zone==='bowl'){const n=state.items.filter(i=>i.zone==='bowl'&&i!==item).length;x=1.4+Math.cos(n*2.4)*.4;z=2.4+Math.sin(n*2.4)*.4;y=.26+Math.min(n,8)*.04;}
 else{x=point?.x??-2.4+Math.random();z=point?.z??Math.random()*2-1;y=.03;}
 g.userData.target.set(x,y,z);refresh();if(item.dish)showReview(item.dish);announce(zone==='bowl'?'Served.':zone==='pan'?(state.burner?'Sizzling…':'Turn on the burner.'):'');return true;}
function setBurner(){state.burner=!state.burner;toggle.setAttribute('aria-pressed',state.burner);toggle.querySelector('span:nth-child(2)').textContent=state.burner?'Burner on':'Burner off';root.querySelector('.heat-message').textContent=state.burner?'Heating':'Paused';flames.visible=state.burner;fireLight.intensity=state.burner?2:0;knobLine.rotation.z=state.burner?-1.2:0;announce('');}
toggle.addEventListener('click',setBurner);root.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{const item=state.items.find(i=>String(i.id)===select.value);if(item)put(item,b.dataset.move);}));
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-.9);let drag=null;
function cast(e){const b=host.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const p=new THREE.Vector3();ray.ray.intersectPlane(plane,p);p.x=THREE.MathUtils.clamp(p.x,-4.7,4.7);p.z=THREE.MathUtils.clamp(p.z,-3.7,3.7);return p;}
function startDrag(item,e,fromShelf=false){drag={item,startX:e.clientX,startY:e.clientY,moved:false,fromShelf,oldZone:item.zone};document.body.classList.add('food-dragging');if(!fromShelf)state.move(item,'counter');select.value=item.id;}
const thumbs=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});thumbs.setSize(200,160);thumbs.toneMapping=THREE.ACESFilmicToneMapping;thumbs.toneMappingExposure=1.1;
for(const spec of ingredients){const b=document.createElement('button');b.className='ingredient-button';b.type='button';const thumb=document.createElement('canvas');thumb.width=200;thumb.height=160;thumb.setAttribute('aria-hidden','true');b.append(thumb);drawThumb(spec,thumb,b);b.setAttribute('aria-label',`Add ${spec.name} to pan, or drag onto counter`);b.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();const item=newFood(spec.id);if(item){startDrag(item,e,true);b.setPointerCapture(e.pointerId);}});b.addEventListener('click',e=>{if(e.detail===0){const item=newFood(spec.id);if(item)put(item,'pan');}});shelf.append(b);}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;cast(e);const hits=ray.intersectObjects([...objects.values()],true);if(hits.length){let obj=hits[0].object;while(!obj.userData.item&&obj.parent)obj=obj.parent;if(obj.userData.item){e.preventDefault();startDrag(obj.userData.item,e);renderer.domElement.setPointerCapture(e.pointerId);}}else if(ray.intersectObject(knob).length)setBurner();});
addEventListener('pointermove',e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>6)drag.moved=true;if(drag.moved){const p=cast(e),g=objects.get(drag.item.id);g.userData.target.set(p.x,1.5,p.z);}}, {passive:true});
addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;document.body.classList.remove('food-dragging');if(!d.moved){if(d.fromShelf)put(d.item,'pan');else put(d.item,d.oldZone);return;}const p=cast(e),zone=Math.hypot(p.x-1.3,p.z+1.5)<1.55?'pan':Math.hypot(p.x-1.4,p.z-2.4)<1.2?'bowl':'counter';if(!put(d.item,zone,p))put(d.item,'counter',new THREE.Vector3(-1.3,0,2.4));});
addEventListener('pointercancel',()=>{if(drag){put(drag.item,drag.oldZone);drag=null;}document.body.classList.remove('food-dragging');});
root.querySelector('.kitchen-reset').addEventListener('click',()=>{drag=null;document.body.classList.remove('food-dragging');for(const g of objects.values()){scene.remove(g);g.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}objects.clear();state.reset();flames.visible=false;fireLight.intensity=0;toggle.setAttribute('aria-pressed','false');toggle.querySelector('span:nth-child(2)').textContent='Burner off';root.querySelector('.heat-message').textContent='Ready when you are.';refresh();announce('');root.querySelector('.dish-review').hidden=true;});
function resize(){const w=host.clientWidth,h=host.clientHeight,ww=w<500?9.3:11.8;camera.left=-ww/2;camera.right=ww/2;camera.top=ww*h/w/2;camera.bottom=-camera.top;camera.updateProjectionMatrix();renderer.setSize(w,h,false);}new ResizeObserver(resize).observe(host);resize();refresh();
let last=0,raf=0,active=false,uiClock=0;
function animate(now){if(!active){raf=0;return;}const dt=Math.min((now-last)/1000||0,.05);last=now;const cooked=state.tick(dt);if(cooked.length)finishDish();
 const cooking=state.items.some(i=>i.zone==='pan'&&!i.cooked)&&state.burner;
 for(const item of state.items){const g=objects.get(item.id);g.position.lerp(g.userData.target,reduced?1:1-Math.exp(-dt*16));const spec=ingredients.find(i=>i.id===item.type);for(const c of (item.dish?[]:g.userData.colors))c.material.color.copy(c.base).lerp(new THREE.Color(spec.done),item.progress*.7);if(!item.dish&&(item.type==='chocolate'||item.type==='cheese'))g.scale.y=1-item.progress*.55;if(!reduced&&state.burner&&item.zone==='pan')g.position.y+=Math.sin(now*.022+item.id)*.005;}
 pan.rotation.z=state.burner&&!reduced?Math.sin(now*.015)*.004:0;
 if(state.burner&&!reduced)flames.children.forEach((f,i)=>f.scale.y=.8+Math.sin(now*.009+i)*.22);
 steam.forEach((s,i)=>{const phase=(now*.00035+i/steam.length)%1;s.visible=cooking&&!reduced;s.position.set(1.3+Math.sin(i*12.3+phase)*.65,1.1+phase*1.6,-1.5+Math.cos(i*3.7)*.55);s.scale.setScalar(.5+phase*1.9);s.material.opacity=(1-phase)*.18;});
 uiClock+=dt;if(uiClock>.3){uiClock=0;const inPan=state.items.filter(i=>i.zone==='pan'&&!i.cooked);if(inPan.length&&state.burner){const pct=Math.round(inPan.reduce((v,i)=>v+i.progress,0)/inPan.length*100);root.querySelector('.heat-message').textContent=`Sizzling · ${pct}%`;}}
 renderer.render(scene,camera);raf=requestAnimationFrame(animate);}
const observe=new IntersectionObserver(entries=>{active=entries[0].isIntersecting&&!document.hidden;if(active&&!raf){last=performance.now();raf=requestAnimationFrame(animate);}}, {rootMargin:'150px'});observe.observe(host);document.addEventListener('visibilitychange',()=>{active=!document.hidden&&host.getBoundingClientRect().bottom>0&&host.getBoundingClientRect().top<innerHeight+150;if(active&&!raf){last=performance.now();raf=requestAnimationFrame(animate);}});

function drawThumb(spec,canvas,button){
 const sc=new THREE.Scene();sc.add(new THREE.HemisphereLight(0xffffff,0x736a52,3));const light=new THREE.DirectionalLight(0xffeedb,3);light.position.set(-3,5,4);sc.add(light);const cam=new THREE.PerspectiveCamera(35,1.25,.1,30);cam.position.set(1.1,1.1,1.65);cam.lookAt(0,.2,0);const group=buildFood({type:spec.id},true);group.position.set(0,0,0);sc.add(group);const ctx=canvas.getContext('2d');let frame=0,start=0;
 const paint=()=>{thumbs.render(sc,cam);ctx.clearRect(0,0,200,160);ctx.drawImage(thumbs.domElement,0,0);};paint();
 function spin(t){group.rotation.y=Math.sin((t-start)*.0015)*.4;paint();frame=requestAnimationFrame(spin);}
 button.addEventListener('pointerenter',()=>{if(!reduced&&!frame){start=performance.now();frame=requestAnimationFrame(spin);}});button.addEventListener('pointerleave',()=>{cancelAnimationFrame(frame);frame=0;group.rotation.y=0;paint();});
}
function showReview(dish){const review=root.querySelector('.dish-review');review.hidden=false;review.classList.toggle('bad-dish',dish.bad);review.querySelector('.dish-verdict').textContent=dish.bad?'Chef, explain yourself.':'Chef’s verdict';review.querySelector('h3').textContent=dish.name;review.querySelector('p').textContent=dish.comment;if(!reduced)review.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'none'}],{duration:400,easing:'ease-out'});}
function finishDish(){
 const batch=state.items.filter(i=>i.zone==='pan'&&!i.dish);if(!batch.length||batch.some(i=>!i.cooked))return;
 const dish=recipeFor(batch.map(i=>i.type)),item=batch[0],old=objects.get(item.id),position=old.position.clone();
 for(const i of batch){const g=objects.get(i.id);scene.remove(g);g.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});objects.delete(i.id);}
 state.items=state.items.filter(i=>!batch.includes(i)||i===item);item.dish=dish;const g=new THREE.Group();g.userData.item=item;g.userData.colors=[];g.position.copy(position);g.userData.target=new THREE.Vector3(1.3,.9,-1.5);
 const disc=(radius,height,color,y)=>mesh(new THREE.CylinderGeometry(radius,radius*.96,height,48),mat(color),g,0,y,0);
 if(dish.look==='pancake'||dish.look==='bread'){for(let n=0;n<(dish.look==='pancake'?3:1);n++)disc(.66,.12,0xd79a45,.08+n*.13);box(g,.2,.055,.17,0xffe48c,0,dish.look==='pancake'?.43:.17,0);}
 else if(dish.look==='brownie'){box(g,1.05,.28,.85,0x4e2819,0,.15,0);for(let n=0;n<9;n++)ball(g,.045,0xa36a42,(n%3-1)*.29,.3,(Math.floor(n/3)-1)*.23);}
 else if(dish.look==='omelette'){ball(g,.64,0xf2bd41,0,.13,0,1.2,.28,.75);for(let n=0;n<9;n++)box(g,.07,.015,.045,n%2?0x3e7735:0xed6541,Math.sin(n*7)*.42,.27,Math.cos(n*4)*.27);}
 else if(dish.look==='steak'){ball(g,.62,0x93502c,0,.16,0,1.1,.28,.8);for(let n=0;n<4;n++){const stripe=box(g,.7,.012,.04,0x49291c,0,.32,(n-1.5)*.16);stripe.rotation.y=.3;}for(let n=0;n<4;n++)ball(g,.13,0x4b8a35,.55,.14,(n-1.5)*.25);}
 else if(dish.look==='soup'||dish.look==='fondue'){disc(.76,.08,dish.look==='fondue'?0x512e1d:0xe5a643,.06);for(let n=0;n<10;n++)ball(g,.045,dish.look==='fondue'?0x936244:0xffd979,Math.sin(n*7)*.53,.11,Math.cos(n*4)*.53,1,.3,1);}
 else if(dish.look==='shrimp'){for(let n=0;n<5;n++){const s=mesh(new THREE.TorusGeometry(.21,.09,12,24,Math.PI*1.6),mat(0xf08b53),g,Math.cos(n*1.25)*.4,.12,Math.sin(n*1.25)*.4);s.rotation.x=-Math.PI/2;s.rotation.z=n;}}
 else if(dish.look==='disaster'){ball(g,.66,0x44472c,0,.14,0,1,.25,.9);for(let n=0;n<8;n++)ball(g,.15,n%2?0x29231f:0x817347,Math.sin(n*7)*.43,.22,Math.cos(n*4)*.43,1,.7,1);}
 else{for(let n=0;n<12;n++)ball(g,dish.look==='fritter'?.2:.15,dish.look==='fritter'?0xd49b3e:[0x4b8a35,0xda7433,0xbe4e2b][n%3],Math.sin(n*7)*.52,.12+(n%3)*.04,Math.cos(n*4)*.52,1,.65,1);}
 scene.add(g);objects.set(item.id,g);select.value=item.id;refresh();showReview(dish);announce('Ready.');
}
